[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pypi-cache"
version = "0.0.2"
authors = [
  { name="German Navarro", email="ge.najim@gmail.com" },
]
description = "An utility to generate a local PyPI cache for selected packages based on the PyPI.org repositories."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: System :: Archiving :: Mirroring"
]
dependencies = [
  "beautifulsoup4==4.11.1",
  "wheel_filename==1.4.1",
  "multimethod==1.8",
]

[tool.setuptools]
packages = ["pypi_cache"]

[project.urls]
"Homepage" = "https://github.com/UB-Quantic/pypi-cache"

[project.scripts]
pypi-cache = "pypi_cache.cli:cli"

[project.entry-points."pypi_cache.cmd"]
add = "pypi_cache.cmd:Add"
update = "pypi_cache.cmd:Update"

[tool.black]
line-length = 1000